### ISSUE TITLE
Appearances set item crashing the game

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#265]
From Project-Aurora created by [GarzoxShaw](https://github.com/GarzoxShaw): Mike-SPP/Project-Aurora#235  

From the Captive Wyrmtongue <Reluctant 'Quartermaster'> Vendor, these 3 item make the game crash and do not give the appearance to the collection
![image](https://user-images.githubusercontent.com/71578432/95014079-bccc9900-0644-11eb-8889-358f8b7c8355.png)
![image](https://user-images.githubusercontent.com/71578432/95014053-973f8f80-0644-11eb-808d-65054f528557.png)
![image](https://user-images.githubusercontent.com/71578432/95014057-9ad31680-0644-11eb-92ec-458fcf23d8d4.png)
![image](https://user-images.githubusercontent.com/71578432/95014061-9c9cda00-0644-11eb-95de-537302ed6e07.png)

[2020-10-04 13.18.18 Crash - 9672.txt](https://github.com/Mike-SPP/Project-Aurora/files/5323089/2020-10-04.13.18.18.Crash.-.9672.txt)
[2020-10-04 13.19.26 Crash - 2532.txt](https://github.com/Mike-SPP/Project-Aurora/files/5323090/2020-10-04.13.19.26.Crash.-.2532.txt)
[2020-10-04 13.19.59 Crash - 1352.txt](https://github.com/Mike-SPP/Project-Aurora/files/5323091/2020-10-04.13.19.59.Crash.-.1352.txt)

**Comment by sausagemadness** [comment]
I did encounter this issue as a demon hunter

**Comment by sausagemadness** [comment]
Did not encounter this issue while using my rogue.

**Comment by acidmanifesto** [comment]
i looked into this. the items will only crash if you consume it for a character who does not support the armor type. the items are not faulty at all and it only results in a client crash, consuming the item with the correct armor class race will give all the appearences associated to that player.

**Comment by sausagemadness** [comment]
Could it be possible to change the ability of the classes that do not support it to not use it?

**Comment by acidmanifesto** [comment]
i would have to refer to duff or joey about the bitmasking\restricting it to certain classes.

**Comment by Duff-SPP** [comment]
Ill send what i said to mdic ^^

Characters have a default value / code that allows them to only use 1 type of armor
(Main Armor Profficiencys)
druid = leather
Paladin = Plate
All charactrers have their OFF Armor Proficiency, hence you can use cloth on paladin aswell


BUT classes are bound to a default Amor Proficiency

Iknow this because i have tried very hard for very long to allow a Rogue that uses leather to tmog his leather items into plate items and also allow him to use plate items wich he then can tmog into lether etc etc---- But this all requires SRC Edits to Change the Default/Standard Amor Profficiency... This can be done by The One and Only Our Lord Mdic!

The fix here will either be to allow all classes to use all armor profficiencys as their MAIN

Or then the fix would be to rename the description of the item to say

ONLY USEABLE BY "CLASS" IF USED BY CLASSES THAT CANT USE THE ARMOR TYPE U WILL CRASH
It could also be the script/Spell itself, but i see that there is 0 issues on classes that can use the amor
its just when a class that cant use it uses it then they crashes


So we either gonna allow all classes to use all proffiency or we just have to rename the item to inform people about it

**Comment by Fransango** [comment]
That happens w all appearance unlocker items, like ashran ones as example

**Comment by Fransango** [comment]
![imagen](https://user-images.githubusercontent.com/35998435/112677080-8fc9a800-8e69-11eb-9e0d-6f6d14742813.png)
Another crasher item: area 52

**Comment by Fransango** [comment]
![imagen](https://user-images.githubusercontent.com/35998435/112681193-a3c3d880-8e6e-11eb-8b56-5bd7cc730a82.png)
Another item that crash from area 52

**Comment by sausagemadness** [comment]
I think the issue is that the sets are giving items that are not equip-able by that class. Maybe make exclusions for each class?

**Comment by acidmanifesto** [comment]
Got the fel ensemble items locked to the right classes to prevent crashing. will work on the other items list u provided later on
